# Generated by Django 5.0.6 on 2024-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time of post creation')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time of the latest edit to the post')),
                ('title', models.CharField(help_text='The title of the post', max_length=4096)),
                ('slug', models.SlugField(help_text='An identifier for the post, can only contain letters, numbers, underscores or hyphens', unique=True)),
                ('description', models.TextField(help_text='A description of the content of the post')),
                ('body', models.TextField(help_text='The body of the post, markdown format is supported')),
            ],
        ),
    ]
